/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnimeList.Vista;

import AnimeList.App.App;


/**
 *La clase ActualizarAnime nos permite cambiar las variables de un Anime.
 * @author Miguel
 */
public class ActualizarAnime extends javax.swing.JFrame {

    /**
     * Creates new form ActulalizarAnime
     * Ponemos la ventana en el centro de la pàntalla; utilizamos este metodo poque no podemos 
     * reescalar la ventana.
     */
    public ActualizarAnime() {
   
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        capitulos = new javax.swing.JSpinner();
        tituloNuevo = new javax.swing.JTextField();
        generos = new javax.swing.JComboBox<>();
        tituloViejo = new javax.swing.JTextField();
        puntuacion = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cambiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        capitulos.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(capitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 50, 30));
        getContentPane().add(tituloNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 270, 30));

        generos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mecha", "shonen", "shojo", "seinen" }));
        getContentPane().add(generos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, 30));
        getContentPane().add(tituloViejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 270, 30));

        puntuacion.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 220, 50));

        cambiar.setText("Cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });
        getContentPane().add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 90, 30));

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Anime:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo Titulo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 234, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/evangelion2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Enlazo el menu con el boton de salir
     * @param evt 
     */
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
         menu.show();
         dispose();
    }//GEN-LAST:event_salirActionPerformed
    /**
     * Capturamos el evento al pulsar el boton actualizar 
     * Recogemos todos los campos en las variables y los mandamos al metodo updateAnime
     * al inicializar con una instancia de App
     * @param evt 
     */
    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        // TODO add your handling code here:
        App app = new App();
        
            String cad1 = tituloViejo.getText();
            String cad2 = (String) generos.getSelectedItem();
            int puntua = (Integer) puntuacion.getValue();
            String anime = tituloNuevo.getText();
            int capi = (Integer) capitulos.getValue();
        
            
            app.updateAnime(cad1, cad2, anime, puntua, capi);
            System.out.println(app.getAnimes());
    }//GEN-LAST:event_cambiarActionPerformed

    /**
     * Main que nos hace ide para poder lanzar el JFrame y probarlo , muy util para desarollar
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiar;
    private javax.swing.JSpinner capitulos;
    private javax.swing.JComboBox<String> generos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner puntuacion;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tituloNuevo;
    private javax.swing.JTextField tituloViejo;
    // End of variables declaration//GEN-END:variables
}
