/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnimeList.Vista;

import AnimeList.App.App;

/**
 *La clase SortAnime ordena la lista de Anime segun el parametro que seleccionemos.
 * @author Miguel
 */
public class SortAnime extends javax.swing.JFrame {

    /**
     * Creates new form SortAnime
     * Ponemos la ventana en el centro de la pàntalla; utilizamos este metodo poque no podemos 
     * reescalar la ventana.
     */
    public SortAnime() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salir = new javax.swing.JButton();
        capitulo = new javax.swing.JButton();
        puntuacion = new javax.swing.JButton();
        genero = new javax.swing.JButton();
        titulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 490, 80, 30));

        capitulo.setText("Por Capitulo");
        capitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capituloActionPerformed(evt);
            }
        });
        getContentPane().add(capitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 220, 40));

        puntuacion.setText("Por puntuacion");
        puntuacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntuacionActionPerformed(evt);
            }
        });
        getContentPane().add(puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, 40));

        genero.setText("Por Generro");
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 220, 40));

        titulo.setText("Por Titulo");
        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ordenar.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Capturamos evento que nos pide ordenar por puntuacion y llamamos a su respectiva funcion de App
     * @param evt 
     */
    private void puntuacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntuacionActionPerformed
        // TODO add your handling code here:
        
        App app = new App();
        
        app.ordenarPuntuacion();
        System.out.println(app.getAnimes());
        
    }//GEN-LAST:event_puntuacionActionPerformed
    /**
     * Enlazo el menu con el boton de salir
     * @param evt 
     */
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
         menu.show();
         dispose();        
    }//GEN-LAST:event_salirActionPerformed
    /**
     * Capturamos evento que nos pide ordenar por Titulo y llamamos a su respectiva funcion de App
     * @param evt 
     */
    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed
        // TODO add your handling code here:
        App app = new App();
        
        app.ordenarTitulo();
        System.out.println(app.getAnimes());
    }//GEN-LAST:event_tituloActionPerformed
    /**
     * Capturamos evento que nos pide ordenar por Genero y llamamos a su respectiva funcion de App
     * @param evt 
     */
    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
        App app = new App();
        
        app.ordenarGenero();
        System.out.println(app.getAnimes());
    }//GEN-LAST:event_generoActionPerformed
    /**
     * Capturamos evento que nos pide ordenar por Capitulo y llamamos a su respectiva funcion de App
     * @param evt 
     */
    private void capituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capituloActionPerformed
        // TODO add your handling code here:
        App app = new App();
        
        app.ordenarCapitulo();
        System.out.println(app.getAnimes());
    }//GEN-LAST:event_capituloActionPerformed

    /**
     * Main que nos hace ide para poder lanzar el JFrame y probarlo , muy util para desarollar
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortAnime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortAnime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capitulo;
    private javax.swing.JButton genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton puntuacion;
    private javax.swing.JButton salir;
    private javax.swing.JButton titulo;
    // End of variables declaration//GEN-END:variables
}
